/**
 * TempApi
 * This is a sample openApi document
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: lampralexandros@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The Welcome model module.
 * @module model/Welcome
 * @version 1.0.0
 */
class Welcome {
    /**
     * Constructs a new <code>Welcome</code>.
     * @alias module:model/Welcome
     * @param welcomeTitle {String} 
     */
    constructor(welcomeTitle) { 
        
        Welcome.initialize(this, welcomeTitle);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, welcomeTitle) { 
        obj['welcomeTitle'] = welcomeTitle;
    }

    /**
     * Constructs a <code>Welcome</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/Welcome} obj Optional instance to populate.
     * @return {module:model/Welcome} The populated <code>Welcome</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new Welcome();

            if (data.hasOwnProperty('_id')) {
                obj['_id'] = ApiClient.convertToType(data['_id'], 'String');
            }
            if (data.hasOwnProperty('welcomeTitle')) {
                obj['welcomeTitle'] = ApiClient.convertToType(data['welcomeTitle'], 'String');
            }
        }
        return obj;
    }


}

/**
 * @member {String} _id
 */
Welcome.prototype['_id'] = undefined;

/**
 * @member {String} welcomeTitle
 */
Welcome.prototype['welcomeTitle'] = undefined;






export default Welcome;

