/**
 * TempApi
 * This is a sample openApi document
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: lampralexandros@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The Wev model module.
 * @module model/Wev
 * @version 1.0.0
 */
class Wev {
    /**
     * Constructs a new <code>Wev</code>.
     * @alias module:model/Wev
     * @param tile {String} 
     */
    constructor(tile) { 
        
        Wev.initialize(this, tile);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, tile) { 
        obj['tile'] = tile;
    }

    /**
     * Constructs a <code>Wev</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/Wev} obj Optional instance to populate.
     * @return {module:model/Wev} The populated <code>Wev</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new Wev();

            if (data.hasOwnProperty('_id')) {
                obj['_id'] = ApiClient.convertToType(data['_id'], 'String');
            }
            if (data.hasOwnProperty('tile')) {
                obj['tile'] = ApiClient.convertToType(data['tile'], 'String');
            }
        }
        return obj;
    }


}

/**
 * @member {String} _id
 */
Wev.prototype['_id'] = undefined;

/**
 * @member {String} tile
 */
Wev.prototype['tile'] = undefined;






export default Wev;

