/**
 * TempApi
 * This is a sample openApi document
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: lampralexandros@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', process.cwd()+'/src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require(process.cwd()+'/src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.TempApi);
  }
}(this, function(expect, TempApi) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new TempApi.WelcomeApi();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('WelcomeApi', function() {
    describe('createwelcome', function() {
      it('should call createwelcome successfully', function(done) {
        //uncomment below and update the code to test createwelcome
        //instance.createwelcome(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('deletewelcome', function() {
      it('should call deletewelcome successfully', function(done) {
        //uncomment below and update the code to test deletewelcome
        //instance.deletewelcome(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('getAllwelcome', function() {
      it('should call getAllwelcome successfully', function(done) {
        //uncomment below and update the code to test getAllwelcome
        //instance.getAllwelcome(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('getByParamswelcome', function() {
      it('should call getByParamswelcome successfully', function(done) {
        //uncomment below and update the code to test getByParamswelcome
        //instance.getByParamswelcome(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('getwelcome', function() {
      it('should call getwelcome successfully', function(done) {
        //uncomment below and update the code to test getwelcome
        //instance.getwelcome(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('updatewelcome', function() {
      it('should call updatewelcome successfully', function(done) {
        //uncomment below and update the code to test updatewelcome
        //instance.updatewelcome(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
  });

}));
